### ISSUE TITLE
Running actual Lambda functions in microVMs

### ISSUE THREAD

**Issue by MadhavChoudhary** [firecracker-microvm/firecracker-demo#13]
Wouldn't it be more interesting to test the performance of some actual lambda functions in Firecracker? Did anyone try?
I would go with installing [docker-lambda](https://github.com/lambci/docker-lambda) in the root-fs, since it is made clear that it simulates the exact environment of an actual lambda function.
But installing docker and running it on such a small root-fs of the microvm would be a pain.
Could anyone help me with how this can be achieved?

**Comment by acatangiu** [comment]
@MadhavChoudhary sorry for the late response. What you are suggesting is a complex scenario which is out of scope for this demo IMHO.

But you should be able to do this as an exercise if you want.

> But installing docker and running it on such a small root-fs of the microvm would be a pain.

The root-fs can be resized. You can also loop-mount it on the host to set things up easier instead of setting them up directly in the Firecracker guest.

**Comment by Anjali05** [comment]
@MadhavChoudhary Were you able to run docker successfully?

**Comment by MadhavChoudhary** [comment]
@Anjali05 No. 
It was not just a problem of root-fs size. Docker service couldn't be started for some reason.

**Comment by Anjali05** [comment]
@MadhavChoudhary Yeah, even for me docker keeps crashing for some reason. I have resized the image and increased the memory also but still, it does not seem to work.
@acatangiu Would it be possible to get some insights on this?

**Comment by acatangiu** [comment]
@Anjali05 @MadhavChoudhary I'm sorry guys, but that looks like a docker issue. I'm not a docker expert and never had a case to run docker *inside* a Firecracker microVM so I can't help.

I'm wondering though, what are you trying to do? As I said, Docker _inside_ Firecracker is not a use-case we've seen before.

Firecracker **micro**VMs are meant to provide container-like speed and virtualization-level security. The general usecase is running a workload in a microVM _instead_ of a container. That's why I don't understand your usecase of running a workload in a container in a microVM.

**Comment by MadhavChoudhary** [comment]
It was said that firecracker is being used in production in AWS Lambda.
I wanted to simulate the same environment using firecracker microVM.
To get a perfect simulation I wanted to run [docker-lambda](https://github.com/lambci/docker-lambda) which is said to simulate AWS Lambda environment almost identically inside the microVM after boot up.

**Comment by Anjali05** [comment]
@acatangiu I want to run few benchmarks and they have docker images for that which I thought is the easiest to set up. Building them from source would be difficult so I wanted to run the images directly.

**Comment by acatangiu** [comment]
I see. What is the problem? What is `docker` reporting?

**Comment by Anjali05** [comment]
@acatangiu So here is whats happening with my setup. It looks like it works when I start docker with `dockerd` command instead of using `service start docker`. The first time it starts immediately but when I reboot the microVM it takes like 10 mins to start it and I keep getting this message on the terminal: 
`crypto/rand: blocked for 60 seconds waiting to read random data from the kernel`


![docker-3](https://user-images.githubusercontent.com/8316863/62797870-6eeced00-baa2-11e9-9ab6-ecf3a43dbb07.png)

**Comment by Anjali05** [comment]
@acatangiu It looks like some entropy problem. I added the ring-tools package to make sure there is enough entropy to support `/dev/urandom `but when I try to start the service it fails:

![rngd](https://user-images.githubusercontent.com/8316863/62799578-cc833880-baa6-11e9-9a96-9677c9c5be0b.png)

**Comment by Anjali05** [comment]
@acatangiu I added `heveged` package to make sure there is enough entropy and docker seems to be running properly now.

**Comment by acatangiu** [comment]
Indeed, initial entropy is something you need to manage in Firecracker. Please see https://github.com/firecracker-microvm/firecracker/issues/663 for current progress on the topic.

Closing this issue on the demo, feel free to reopen.
