### ISSUE TITLE
Rootfs image

### ISSUE THREAD

**Issue by Anjali05** [firecracker-microvm/firecracker-demo#14]
Just curious as to why the same rootfs image is used in starting all the firecracker instances. I see a script for copying rootfs but I do not think it is being used in the actual run. Also, will sharing the same image(instead of making a copy) across all the VMs will have any affect on any performance measurements?

**Comment by acatangiu** [comment]
All microVMs are run using the same guest contents (scripts and workload packed in the `xenial.rootfs.ext4` read-only drive) for the practical reason of keeping the demo simple. Each workload is simply doing random network traffic.

The script for copying rootfs is not used, but left there as a helper script. All microVMs actually **do share** the same RO disk file.

Duplicating that file would be wasteful and would also possibly impact performance since not all microVMs might be able to have theirs in the host page cache.

**Comment by acatangiu** [comment]
Closing this, feel free to re-open if you have further questions.
