### ISSUE TITLE
Guest-boot-time around 800ms

### ISSUE THREAD

**Issue by joehattori** [firecracker-microvm/firecracker-demo#44]
I executed the following commands to measure the startup time of a single microVM, and it seems like it takes around 800ms to boot according to the output at `output/fc-sb0-log`.
```bash
sudo ./0.initial-setup.sh 1
sudo ./start-firecracker.sh
```
My laptop is Ubuntu 20.04 with 4-core Intel i7 (3.0GHz), but is this the expected behavior? Is there any way to make the boot time shorter, hopefully ~200ms?

**Comment by acatangiu** [comment]
Couple of questions:
- What `resources` (firecracker binary version, kernel, rootfs) are you using?
- Are you running with any local changes (to the scripts or otherwise)? If yes, what are those? For example, enabling console will slow things down considerably.
- Do you consistently get `800ms` or is that only on first run? Depending on your SSD/HDD speed, the first run is slow, make sure you have enough RAM to get resources in filesystem cache and look to subsequent run times.

**Comment by joehattori** [comment]
@acatangiu I'm running without any any local changes, so the Firecracker version is v1.0.0, the kernel version is 4.14, and the rootfs is the one located at https://s3.amazonaws.com/spec.ccfc.min/img/alpine_demo/fsfiles/xenial.rootfs.ext4.
I ran `sudo ./start-firecracker.sh` and `sudo killall firecracker`, and then `sudo ./start-firecracker.sh` again (second run), but the boot time is still around 800ms. My machine has 16GB of RAM so I believe it is enough for Firecracker to boot within at least 400ms.

**Comment by acatangiu** [comment]
RIght! It looks like the downloaded kernel image is not optimally built (different kconfig used probably).

Using the [previously committed kernel image](https://github.com/firecracker-microvm/firecracker-demo/blob/c1981fce9ab5019b1c213161f285659b0d525ec7/vmlinux) should bring down your boot-time to under `100ms`.

**Comment by joehattori** [comment]
> @joehattori you can also make [this simple script change](https://github.com/firecracker-microvm/firecracker-demo/pull/45) and get sub-100ms boot time +1

This also made the boot time under 100ms on my laptop as well, thanks again!
